//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id_order { get; set; }
        public int Id_client { get; set; }
        public int Id_avto { get; set; }
        public int Id_service { get; set; }
        public System.DateTime Date_order { get; set; }
        public string Period_of_execution { get; set; }
        public string Order_status { get; set; }
    
        public virtual Avto Avto { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Services Services { get; set; }
    }
}
